site_name: 赵广润的网页
theme: 
  name: material
  language: zh
nav:
  - 主页: index.md
  - mkdocs配置: mkdocs配置.md
  - markdown语法: markdown语法.md
  - 深度学习: 
    - 模型介绍:
      - yolo系列模型: yolo.md
    - LLM技术: 
      - 参数量分析: 参数量分析.md
  - 算法: 
    - 卡尔曼滤波: 卡尔曼滤波.md
markdown_extensions:
  - mdx_math
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
plugins:
  - glightbox
